### ISSUE TITLE
Remove usage of prototype extensions

### ISSUE THREAD

**Issue by truenorth** [cibernox/ember-cpm#119]

**Comment by cibernox** [comment]
Can you explain this a bit more? Are prototype extensions considered harmful?

**Comment by rwjblue** [comment]
@cibernox - New ember-cli addons are generated with prototype extensions disabled.  Mostly because an addon author cannot know if the addon will be consumed with prototype extensions on or off, so it makes sense to be conservative and disable them in the addons own test suite.

**Comment by rwjblue** [comment]
https://github.com/rwjblue/ember-disable-prototype-extensions is included by default for newly generated addons.

**Comment by cibernox** [comment]
Understood. Added to the pipeline

**Comment by cibernox** [comment]
Added the addon in https://github.com/cibernox/ember-cpm/commit/cacc14b4830cfba61f4146df71e076d7655392ad and all tests are still green.

I haven't found any evident place were prototype extensions are being used.  Closing this with no work :)

**Comment by truenorth** [comment]
Thanks @cibernox!
